version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started
      - ng build

  post_build:
    commands:
      - mv appspec.yml ./dist
      - mv scripts ./dist
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: no
